name: 🐞 Bug Report
description: Describe the problem
labels: ["bug", "package: app"]
body:
  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of the App do you use?
      placeholder: 1.2.3 ← should look like this
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: How can we see what you're seeing? Specific is terrific.
      placeholder: |-
        1. foo
        2. bar
        3. baz
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Result
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Result
      description: Logs? Screenshots? Yes, please.
    validations:
      required: true

  - type: textarea
    id: passkit_file
    attributes:
      label: Upload ".pkpass" or ".pkpasses" file
      description: If possible & relevant, please attach the non-working file. Change the file extension to zip and drop it into this field.
    validations:
      required: false