name: 🐞 Bug Report
description: Describe the problem
labels: ["bug"]
body:
  - type: dropdown
    id: environment
    attributes:
      label: Platform
      description: Which platform do you use?
      options:
        - Dart
        - Dart Web
        - Flutter Mobile
        - Flutter Desktop
        - Flutter Web
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of Flutter do you use?
      placeholder: 1.2.3 ← should look like this
    validations:
      required: true

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package has a bug?
      options:
        - passkit
        - passkit_ui
        - apple_passkit
        - (app)
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: How can we see what you're seeing? Specific is terrific.
      placeholder: |-
        1. foo
        2. bar
        3. baz
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Result
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Result
      description: Logs? Screenshots? Yes, please.
    validations:
      required: true

  - type: textarea
    id: passkit_file
    attributes:
      label: Upload ".pkpass" or ".pkpasses" file
      description: If possible & relevant, please attach the non-working file. Change the file extension to zip and drop it into this field.
    validations:
      required: false