include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    unawaited_futures: true
    sort_constructors_first: true
    use_key_in_widget_constructors: true
    use_super_parameters: true
    use_colored_box: true
    use_decorated_box: true
    no_leading_underscores_for_local_identifiers: true
    require_trailing_commas: true
    flutter_style_todos: true
    sort_pub_dependencies: true

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
