name: passkit_server
description: Easily add Apple's PassKit API endpoints to your server.
version: 0.0.1
repository: https://github.com/ueman/passkit
topics:
  - passkit
  - pkpass
  - backend

environment:
  sdk: ^3.4.0

dependencies:
  passkit: ^0.0.7
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
