name: passkit_server
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/ueman/passkit

environment:
  sdk: ^3.4.4

dependencies:
  passkit: ^0.0.4
  shelf: ^1.4.2
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0