name: passkit_ui

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "passkit_ui/**"
      - ".github/workflows/passkit_ui.yaml"
    branches:
      - master

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_version: 3.22.2
      working_directory: passkit_ui
      min_coverage: 20
