name: semantic_pull_request

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1
